name: looksee-trip
version: 0.7.0

github: ejconlon/looksee
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2023 Eric Conlon
synopsis: A simple text parser with decent errors
description: Please see the README on GitHub at <https://github.com/ejconlon/looksee#readme>
tested-with: GHC == 9.8.4
category: Parsing

defaults:
  local: ../defaults.yaml

extra-source-files:
- README.md

dependencies:
- base >= 4.12 && < 5
- daytripper >= 0.4 && < 0.5
- looksee >= 0.7 && < 0.8
- prettyprinter >= 1.7 && < 1.8
- prop-unit >= 0.2 && < 0.3
- text >= 2.0 && < 2.2

library:
  source-dirs: src

