name: looksee-trip
version: 0.6.0

github: ejconlon/looksee
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2023 Eric Conlon
synopsis: A simple text parser with decent errors
description: Please see the README on GitHub at <https://github.com/ejconlon/looksee#readme>
tested-with: GHC == 9.6.3
category: Parsing

defaults:
  local: ../defaults.yaml

extra-source-files:
- README.md

dependencies:
- base >= 4.12 && < 5
- daytripper >= 0.3 && < 0.4
- looksee >= 0.6 && < 0.7
- prettyprinter >= 1.7 && < 1.8
- text >= 2.0 && < 2.1

library:
  source-dirs: src

