name: looksie
version: 0.1.0

github: ejconlon/looksie
license: AllRightsReserved
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2023 Eric Conlon
synopsis: parser with looksie
description: Please see the README on GitHub at <https://github.com/ejconlon/looksie#readme>
tested-with: GHC == 9.2.7

language: GHC2021

extra-source-files:
- README.md

dependencies:
- base >= 4.12 && < 5
- bifunctors >= 5.5 && < 5.6
- containers >= 0.6 && < 0.7
- errata >= 0.4 && < 0.5
- mmorph >= 1.2 && < 1.3
- mtl >= 2.2 && < 2.3
- recursion-schemes >= 5.2 && < 5.3
- scientific >= 0.3 && < 0.4
- text >= 1.2 && < 2.1
- vector >= 0.12 && < 0.13

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  looksie-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - looksie
    - tasty
    - tasty-hunit
