resolver: nightly-2026-05-27

ghc-options:
  "$everything": -haddock

allow-newer: true
allow-newer-deps:
- errata

packages:
- looksee
- looksee-trip

extra-deps:
- daytripper-1.0.1
- errata-0.4.0.3
- prop-unit-1.0.2
