resolver: lts-22.13

ghc-options:
  "$everything": -haddock

allow-newer-deps:
- falsify

packages:
- looksee
- looksee-sexp
- looksee-trip

extra-deps:
- bowtie-0.2.0
- errata-0.4.0.2
- falsify-0.2.0
- daytripper-0.3.1

# TODO Remove when falsify bumps
allow-newer: true
allow-newer-deps:
- falsify
