name: looksee
version: 0.8.0

github: ejconlon/looksee
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2023 Eric Conlon
synopsis: A simple text parser with decent errors
description: Please see the README on GitHub at <https://github.com/ejconlon/looksee#readme>
tested-with: GHC == 9.8.4
category: Parsing

defaults:
  local: ../defaults.yaml

extra-source-files:
- README.md

dependencies:
- base >= 4.12 && < 5
- bifunctors >= 5.5 && < 5.7
- containers >= 0.6 && < 0.7
- errata >= 0.4.0.1 && < 0.5
- mmorph >= 1.2 && < 1.3
- mtl >= 2.2 && < 2.4
- recursion-schemes >= 5.2 && < 5.3
- scientific >= 0.3 && < 0.4
- text >= 1.2 && < 2.2
- vector >= 0.12 && < 0.14

library:
  source-dirs: src

tests:
  looksee-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - looksee
    - tasty >= 1.4.3 && < 1.6
    - tasty-hunit >= 0.10 && < 0.11

